apiVersion: v2
appVersion: "1.0"
description: ZeeQS Helm Chart for Kubernetes
name: zeebe-zeeqs-helm
version: 0.0.21
icon: https://zeebe.io/img/zeebe-logo.png
dependencies:
- name: hazelcast
  repository: https://hazelcast-charts.s3.amazonaws.com/
  version: 3.5.0
  condition: "hazelcast.enabled"
- name: jenkins-x-crds
  repository: "https://storage.googleapis.com/jenkinsxio/charts"
  version: 3.0.5  